app/models/categories.py
from .db import get_connection

mydb = get_connection()

class Category:

    def __init__(self, category, description, id=None):
        self.id = id
        self.category = category
        self.description = description

    def save(self):
        # Create a New Object in DB
        if self.id is None:
            with mydb.cursor() as cursor:
                sql = "INSERT INTO categories(category, description) VALUES(%s, %s)"
                val = (self.category, self.description)
                cursor.execute(sql, val)
                mydb.commit()
                self.id = cursor.lastrowid
                return self.id
        # Update an Object
        else:
            with mydb.cursor() as cursor:
                sql = "UPDATE categories SET category = %s, description = %s WHERE id = %s"
                val = (self.category, self.description, self.id)
                cursor.execute(sql, val)
                mydb.commit()
                return self.id
            
    def delete(self):
        with mydb.cursor() as cursor:
            sql = f"DELETE FROM categories WHERE id = { self.id }"
            cursor.execute(sql)
            mydb.commit()
            return self.id
            
    @staticmethod
    def get(id):
        with mydb.cursor(dictionary=True) as cursor:
            sql = f"SELECT category, description FROM categories WHERE id = { id }"
            cursor.execute(sql)
            result = cursor.fetchone()
            print(result)
            category = Category(result["category"], result["description"], id)
            return category
        
    @staticmethod
    def get_all():
        categories = []
        with mydb.cursor(dictionary=True) as cursor:
            sql = f"SELECT id, category, description FROM categories"
            cursor.execute(sql)
            result = cursor.fetchall()
            for item in result:
                categories.append(Category(item["category"], item["description"], item["id"]))
            return categories
    
    @staticmethod
    def count_all():
        with mydb.cursor() as cursor:
            sql = f"SELECT COUNT(id) FROM categories"
            cursor.execute(sql)
            result = cursor.fetchone()
            return result[0]
        
    def __str__(self):
        return f"{ self.id } - { self.category }"

app/views/category_views.py
from flask import Blueprint, render_template, request, redirect, flash, url_for

from models.categories import Category

category_views = Blueprint('category',__name__)

@category_views .route('/categories/')
def categories():
    # Consultar Categorias de DB
    categories = Category.get_all()
    return render_template('category/categories.html', categories=categories)

@category_views .route('/categories/create/', methods=('GET','POST'))
def create_cat():
    if request.method =='POST':
        category = request.form['category']
        description = request.form['description']
        if not category:
            flash('Debes ingresar la categoria')
        elif not description:
            flash('Debes ingresar la decripción')
        else:
            cat=Category(category,description)
            cat.save()
            return redirect(url_for('category.categories'))
    
    return render_template('category/create_cat.html')

@category_views .route('/categories/<int:id>/update/')
def update_cat(id):
    return "Vamos a Actualizar"

@category_views .route('/categories/<int:id>/delete/')
def delete_cat(id):
    cat = Category.get(id)
    cat.delete()
    return redirect(url_for('category.categories'))

app/templates/category/categories.html
{% extends 'base.html' %}

{% block title %}
Categories
{% endblock title %}

{% block content %}
    <h1>Categorias</h1>
    <a href="{{ url_for('category.create_cat') }}" class="btn">Nueva Categoria</a>
    <h2>Lista de Categorias</h2>
    <table id="categories">
        <thead>
            <tr>
                <th>ID</th>
                <th>Categoria</th>
                <th>Descripción</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for cat in categories %}
                <tr>
                    <td>{{ cat.id }}</td>
                    <td>{{ cat.category }}</td>
                    <td>{{ cat.description }}</td>
                    <td>
                        <a href="{{ url_for('category.update_cat', id=cat.id) }}">
                            <i class="fa fa-pencil"></i>
                        </a>
                        <a href="{{ url_for('category.delete_cat', id=cat.id) }}">
                            <i class="fa fa-trash"></i>
                        </a>
                    </td>
                    
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

app/templates/category/create_cat.html
{% extends 'base.html' %}

{% block title %}
Crea Nueva Categoria
{% endblock %}
    
{% block content %}
{% for message in get_flashed_messages() %}
<p>{{ message }}</p>
{% endfor %}
<div class="form-container">
   <form method="post">
        <label for="category">Categoria</label><br>
        <input type="text" 
        name="category" 
        id="category"
        value="{{ request.form['category'] }}"
        required
        placeholder="Categoria"><br>
        <label for="description">Descripción</label><br>
        <input type="text" 
                name="description" 
                id="description"
                value="{{ request.form['description'] }}"
                required
                placeholder="Descripción">
        <input type="submit" value="Guardar" class="btn">
   </form>
</div>
{% endblock %}
    