app/models/categories.py
from .db import get_connection

mydb = get_connection()

class Category:

    def __init__(self, category, description, id=None):
        self.id = id
        self.category = category
        self.description = description

    def save(self):
        # Create a New Object in DB
        if self.id is None:
            with mydb.cursor() as cursor:
                sql = "INSERT INTO categories(category, description) VALUES(%s, %s)"
                val = (self.category, self.description)
                cursor.execute(sql, val)
                mydb.commit()
                self.id = cursor.lastrowid
                return self.id
        # Update an Object
        else:
            with mydb.cursor() as cursor:
                sql = "UPDATE categories SET category = %s, description = %s WHERE id = %s"
                val = (self.category, self.description, self.id)
                cursor.execute(sql, val)
                mydb.commit()
                return self.id
            
    def delete(self):
        with mydb.cursor() as cursor:
            sql = f"DELETE FROM categories WHERE id = { self.id }"
            cursor.execute(sql)
            mydb.commit()
            return self.id
            
    @staticmethod
    def get(id):
        with mydb.cursor(dictionary=True) as cursor:
            sql = f"SELECT category, description FROM categories WHERE id = { id }"
            cursor.execute(sql)
            result = cursor.fetchone()
            print(result)
            category = Category(result["category"], result["description"], id)
            return category
        
    @staticmethod
    def get_all():
        categories = []
        with mydb.cursor(dictionary=True) as cursor:
            sql = f"SELECT id, category, description FROM categories"
            cursor.execute(sql)
            result = cursor.fetchall()
            for item in result:
                categories.append(Category(item["category"], item["description"], item["id"]))
            return categories
    
    @staticmethod
    def count_all():
        with mydb.cursor() as cursor:
            sql = f"SELECT COUNT(id) FROM categories"
            cursor.execute(sql)
            result = cursor.fetchone()
            return result[0]
        
    def __str__(self):
        return f"{ self.id } - { self.category }"

app/views/home_views.py
from flask import Blueprint,render_template

home_views = Blueprint('home',__name__)

@home_views.route("/")
def home():
    name="Jehser Mednieta Ibarra"
    return render_template('home/home.html', name=name)

@home_views.route("/3B/")
def tres():
    alumnos = ['Gaby', 'Adriana','Alicia']
    return render_template('home/tres.html', alumnos=alumnos)

@home_views.route("/contact/")
def contact():
    user = 'Jeshersin'
    return render_template('home/contact.html', user=user)

@home_views.route("/about/")
def about():
    user = 'Jeshersin'
    return render_template('home/about.html', user=user)

app/views/user_views.py
from flask import Blueprint, render_template, url_for, flash, redirect

from models.users import User

from forms.user_forms import LoginForm, RegisterForm

user_views = Blueprint('user', __name__)

@user_views .route('/users/register/', methods=('GET', 'POST'))
def register():
    form = RegisterForm()

    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        email = form.email.data

        user = User(username, password, email)
        user.save()

        return redirect(url_for('user.login'))
    return render_template('user/register.html', form=form)

@user_views .route('/users/login/', methods=('GET', 'POST'))
def login():
    form = LoginForm()

    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        user = User.get_by_password(username, password)
        if not user:
            flash('Verifica tus Datos')
        else:
            return render_template('home/home.html', user=user)
    return render_template('user/login.html', form=form)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <title>{% block tittle %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>
<body>
    <nav>
        <ul>
            <li><a href="{{url_for('home.home')}}">Home</a></li>
            <li><a href="{{url_for('home.tres')}}">3B</a></li>
            <li><a href="{{url_for('home.contact')}}">Contact</a></li>
            <li><a href="{{url_for('home.about')}}">Acerca de </a></li>
            <li><a href="{{url_for('category.categories')}}">Categorias</a></li>
            <li><a href="{{url_for('user.register') }}">Registro</a></li>
            {% if user %}
            <li><a href="#">Logout</a></li>
            {% else %}
            <li><a href="{{url_for('user.loginc') }}">Login</a></li>
            {% endif %}
        </ul>
    </nav>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

app/templates/categories.html
{% extends 'base.html' %}

{% block title %}
Categories
{% endblock title %}

{% block content %}
    <h1>Categorias</h1>
    <a href="{{ url_for('create_cat') }}" class="btn">Nueva Categoria</a>
    <h2>Lista de Categorias</h2>
    <table id="categories">
        <thead>
            <tr>
                <th>ID</th>
                <th>Categoria</th>
                <th>Descripción</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for cat in categories %}
                <tr>
                    <td>{{ cat.id }}</td>
                    <td>{{ cat.category }}</td>
                    <td>{{ cat.description }}</td>
                    <td>Update | Eliminar</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}